version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

  spark:
    image: apache/spark-py:v3.3.0
    container_name: spark
    user: root
    ports:
      - "4040:4040"
      - "8888:8888"
    volumes:
      - ./notebooks:/opt/notebooks
    environment:
      - PYSPARK_PYTHON=python3
      - PYTHONPATH=/opt/spark/python
      - SPARK_JARS_PACKAGES=org.apache.iceberg:iceberg-spark-runtime-3.3_2.12:1.4.2,org.apache.hadoop:hadoop-aws:3.3.2,com.amazonaws:aws-java-sdk-bundle:1.11.1026
    command: >
      /bin/bash -c "
        apt-get update && apt-get install -y wget &&
        pip install --no-cache-dir jupyter py4j pyspark==3.3.0 &&
        wget https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-spark-runtime-3.3_2.12/1.4.2/iceberg-spark-runtime-3.3_2.12-1.4.2.jar -P /opt/spark/jars/ &&
        wget https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.2/hadoop-aws-3.3.2.jar -P /opt/spark/jars/ &&
        wget https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.1026/aws-java-sdk-bundle-1.11.1026.jar -P /opt/spark/jars/ &&
        jupyter notebook --ip=0.0.0.0 --port=8888 --notebook-dir=/opt/notebooks --no-browser --allow-root
      "

volumes:
  minio_data:
